dropdown instance overview
tlebeitsuk/hoster pull request #33
Opened 2024-11-13 07:54 UTC by z3kkeen

closes issue #28

2024-11-13 08:15 UTC, WoIfey commented on src/app/dashboard/[projectId]/page.tsx
> +            const createdDate = new Date(createdAt.time).toLocaleString('fi-US', {
![image](https://github.com/user-attachments/assets/dd7dead1-c9d5-4f43-ba7e-bf262776603b)

Kanske vi använder date-fns för att visa hur länge sedan den var aktiv och skapad i stället för att visa ett datum?
- https://date-fns.org/

2024-11-13 08:41 UTC, WoIfey approved these changes

2024-11-13 08:41 UTC, WoIfey commented on src/app/dashboard/[projectId]/page.tsx
> +            )
Det finns `(, { addSuffix: true })` för "ago" men LGTM!

2024-11-13 08:46 UTC, z3kkeen commented on src/app/dashboard/[projectId]/page.tsx
> +            )
fixat

2024-11-14 08:27 UTC, z3kkeen commented on package.json
> +		"bootstrap-icons": "^1.11.3",
tänkte använda det, men tyckte inte om hur det såg ut

2024-11-14 08:28 UTC, WoIfey commented on package.json
> +		"bootstrap-icons": "^1.11.3",
Vi använder lucide-react ikoner

2024-11-14 08:31 UTC, WoIfey commented on src/app/dashboard/[projectId]/[serverName]/page.tsx
> +                <TableHead className="w-[100px]">Created</TableHead>
Created borde vara mer width
![image](https://github.com/user-attachments/assets/4b6ac4d0-1090-4085-b65b-5202c2571bdd)

2024-11-14 08:32 UTC, WoIfey commented
globals.css borde inte ändras 🤔

2024-11-14 08:38 UTC, WoIfey requested changes

2024-11-14 08:38 UTC, WoIfey commented on src/app/globals.css
#36 #47 har redan ändra färgerna.

2024-11-14 08:38 UTC, WoIfey commented on src/components/sidebar-projects.tsx
#38 har adderat det här.

2024-11-14 09:01 UTC, WoIfey approved these changes
LGTM

2024-11-14 09:40 UTC, tlebeitsuk approved these changes
LGTM

2024-11-14 09:41 UTC, merged