Server overview
tlebeitsuk/hoster pull request #73
Opened 2024-11-27 07:24 UTC by z3kkeen

closes #53

2024-11-27 07:40 UTC, tlebeitsuk requested changes
Breadcrumbs behöver inte finnas på sidan, finns redan i layout.tsx.

2024-11-27 11:57 UTC, WoIfey commented on src/app/dashboard/[projectId]/[serverName]/page.tsx
> +              <p>Used capacity: <b className="text-blue-600">{cpu}</b> GB</p>
%?

2024-11-28 06:22 UTC, tlebeitsuk approved these changes

2024-11-28 06:41 UTC, WoIfey approved these changes

2024-11-28 06:51 UTC, merged